// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrightness():Promise<number>;

export function GetClockType():Promise<string>;

export function GetSystemID():Promise<string>;

export function GetVersion():Promise<string>;

export function Reboot():Promise<void>;

export function SetBrightness(arg1:number):Promise<void>;
