// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrightness() {
  return window['go']['main']['App']['GetBrightness']();
}

export function GetSystemID() {
  return window['go']['main']['App']['GetSystemID']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SetBrightness(arg1) {
  return window['go']['main']['App']['SetBrightness'](arg1);
}
