name: Build Wails App for Raspberry Pi (ARM64)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install GTK & WebKit deps for Wails
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          wails build

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: wails-app-arm64
          path: build/bin/*
