name: Build Wails App for Raspberry Pi (ARM64)

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is_prerelease: ${{ steps.set-prerelease.outputs.is_prerelease }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Fetch branch or PR commit
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin +refs/heads/${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}
            git checkout refs/remotes/origin/${{ github.head_ref }}
          else
            git checkout ${{ github.ref }}
          fi

      - id: get-version
        name: Generate version
        run: |
          version=$(git describe \
                      --tags \
                      --first-parent \
                      --dirty \
                      --match "v[0-9]*.[0-9]*.[0-9]*" \
                      --exclude "v*-*-*")
          echo "version -- $version"
          echo "version=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT
        shell: bash

      - id: set-prerelease
        name: Set pre release
        run: |
          version="${{ steps.get-version.outputs.version }}"
          if [[ "$version" == *"-g"* ]] || [[ "$version" == *"-dirty"* ]]; then
            prerelease=true
          else
            prerelease=false
          fi
          echo "is_prerelease=$prerelease" >> $GITHUB_ENV
          echo "is_prerelease=$prerelease" >> $GITHUB_OUTPUT
        shell: bash

  build-arm64:
    needs: determine-version
    runs-on: ubuntu-22.04-arm
    env:
      GOPRIVATE: github.com/jetclock/*
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git to use Personal Access Token for private modules
        run: |
          # Configure Git to use PAT for private repos
          git config --global url."https://${{ secrets.BUILD_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.BUILD_TOKEN }}@github.com/".insteadOf "git@github.com:"
          
          # Set up credential helper
          git config --global credential.helper store
          echo "https://${{ secrets.BUILD_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials
          
          # Verify configuration
          echo "Git config:"
          git config --global --list | grep url

      - name: Test SDK Access
        run: |
          echo "🔍 Testing access to jetclock-sdk repository..."
          
          # Test GitHub API access to the private repository
          echo "Testing GitHub API access..."
          API_RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token ${{ secrets.BUILD_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/jetclock/jetclock-sdk)
          
          HTTP_CODE="${API_RESPONSE: -3}"
          RESPONSE_BODY="${API_RESPONSE%???}"
          
          echo "HTTP Status Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Successfully accessed jetclock-sdk repository via GitHub API"
          else
            echo "❌ Failed to access jetclock-sdk repository via GitHub API"
            echo "HTTP Code: $HTTP_CODE"
            echo "This indicates an authentication or permission issue with BUILD_TOKEN"
            exit 1
          fi
          
          # Test Git access to the repository
          echo "Testing Git access..."
          echo "Attempting: git ls-remote https://github.com/jetclock/jetclock-sdk.git"
          
          # Try with verbose output to see what's happening
          GIT_OUTPUT=$(git ls-remote "https://github.com/jetclock/jetclock-sdk.git" 2>&1)
          GIT_EXIT_CODE=$?
          
          echo "Git exit code: $GIT_EXIT_CODE"
          echo "Git output: $GIT_OUTPUT"
          
          if [ $GIT_EXIT_CODE -eq 0 ]; then
            echo "✅ Successfully accessed jetclock-sdk repository via Git"
          else
            echo "❌ Failed to access jetclock-sdk repository via Git"
            echo "This indicates a Git authentication issue"
            echo "Trying alternative approach..."
            
            # Try with explicit token in URL
            if git ls-remote "https://${{ secrets.BUILD_TOKEN }}@github.com/jetclock/jetclock-sdk.git" > /dev/null 2>&1; then
              echo "✅ Successfully accessed with explicit token in URL"
            else
              echo "❌ Still failed with explicit token"
              exit 1
            fi
          fi
          
          echo "🎉 All SDK access tests passed!"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install, git, GTK & WebKit deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev git 


      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install shell & build tools
        run: sudo apt-get update && sudo apt-get install -y bash coreutils build-essential

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build Wails app
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          VERSION="${{ needs.determine-version.outputs.version }}"
          IS_PRERELEASE="${{ needs.determine-version.outputs.is_prerelease }}"
          echo "Building for ARM64 with version $VERSION (pre-release: $IS_PRERELEASE)"

          if [ "$IS_PRERELEASE" = "true" ]; then
            wails build -debug -v 2 -ldflags "-X main.version=$VERSION"
          else
            wails build -debug -v 2 -ldflags "-X main.version=$VERSION"
          fi

      - name: Zip built app for artifact
        run: |
          VERSION="${{ needs.determine-version.outputs.version }}"
          ZIP_NAME="jetclock-${VERSION}-linux-arm64.zip"
          mkdir -p dist
          cp build/bin/jetclock dist/jetclock
          cd dist
          zip "$ZIP_NAME" jetclock

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: jetclock-${{ needs.determine-version.outputs.version }}-linux-arm64.zip
          path: dist/jetclock-${{ needs.determine-version.outputs.version }}-linux-arm64.zip